# Generated by Django 2.1.7 on 2019-03-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilebox',
            name='name',
        ),
        migrations.AddField(
            model_name='profilebox',
            name='designation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profilebox',
            name='email_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profilebox',
            name='employee_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilebox',
            name='fax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profilebox',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profilebox',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profilebox',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profilebox',
            name='office_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profilebox',
            name='phone_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profilebox',
            name='research_int1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profilebox',
            name='research_int2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profilebox',
            name='research_int3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profilebox',
            name='research_int4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profilebox',
            name='research_int5',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
